### ISSUE TITLE
Disable rendering when game is unfocused

### ISSUE THREAD

**Issue by rhythm-on-github** [Team-Cubey/cubey#11]
having the game completely stop when minimized would be nice for lowering resource usage
depends on #12 though can work without

**Comment by Hubza** [comment]
would this also occur when the game is unfocused? (meaning clicked off), and would the audio continue to play?

**Comment by dheerajhyper69** [comment]
I would think based on "lowering resource usage" that what it should do is pause the game, and completely stop everything, with an option of letting the audio play in a settings menu that will hopefully exist (_see #12_)

**Comment by Hubza** [comment]
maybe i could do something similar to osu!, with a "volume when unfocused" setting

**Comment by Hubza** [comment]
![image](https://user-images.githubusercontent.com/33783503/97337570-5c61fd80-1878-11eb-86b8-79667e23ad1e.png)

**Comment by dheerajhyper69** [comment]
> maybe i could do something similar to osu!, with a "volume when unfocused" setting

What I was thinking of was more like a checkbox saying "audio when unfocused", but this works too because more options are better

**Comment by Hubza** [comment]
see the image i posted

**Comment by dheerajhyper69** [comment]
Yes I did i can't quote an image so I quoted that instead

**Comment by rhythm-on-github** [comment]
I think "master when unfocused" seems like a good way to implement it, with 0% being completely off, of course

**Comment by rhythm-on-github** [comment]
Actually maybe instead do something more like "% of master when unfocused" (not sure how to phrase it)

Otherwise you could end up making the game louder when unfocused (e.g. "Master" = 20%, "Master when unfocused" = 100%)

**Comment by Hubza** [comment]
some people might enjoy the music in the background, though while playing enjoy it quiet or even off. in this case making the game louder if the unfocused master is louder is intended

**Comment by dusstuiter** [comment]
I mean, maybe make a message that plays like after having the game minimized for a while which has someone speaking and saying "You've had Cubey's Adventures running in the background for a while, maybe you should listen to the soundtrack on Spotify instead."

**Comment by Hubza** [comment]
or maybe just save myself alot of extra code and do it the way i originally was going to and still am going to

**Comment by Hubza** [comment]
seems like unity's gonna fuck us here

**Comment by dheerajhyper69** [comment]
i've def seen games that totally unrender when unfocused. when u alt-tab everything stops and it takes a second to re-render when I get back

**Comment by Hubza** [comment]
was it in unity, though? unity really messes me up in quite a few areas here

**Comment by Hubza** [comment]
fixed, though music may stop. we'll see.

**Comment by Hubza** [comment]
doing this breaks the music player

**Comment by Tanza3D** [comment]
rewrite uses less system resources, will hopefully no longer be an issue. will reopen if it is
