### ISSUE TITLE
Add spawn time countdown

### ISSUE THREAD

**Issue by rhythm-on-github** [Team-Cubey/cubey#14]
It would be nice to have a better indication of the exact time you spawn into the level, because on some levels it's nice to do a jump in the first few frames after spawning

This could for example be a timer with optional decimals

**Comment by Hubza** [comment]
would it go "3 2 1 go" or "3 2 1" and then after a second just autospawn you? maybe the 1 can stay on screen until the player spawns? lots of questions here

**Comment by rhythm-on-github** [comment]
I think it should go "3 2 1 go" (spawning on "go")

**Comment by Hubza** [comment]
the "go" would get in the way of the game until it fades out

**Comment by rhythm-on-github** [comment]
I think the countdown shouldn't obstruct the game too much, or at least that is my preference. I think maybe have it be ~50% transparent from the start and then fade from there could be nice

**Comment by Hubza** [comment]
hmmm. maybe it could also be fixed in place above cubey, kinda small. see attached image
![image](https://user-images.githubusercontent.com/33783503/97228064-4861c180-17ce-11eb-9ba1-bc158a8df8b2.png)

**Comment by rhythm-on-github** [comment]
Oh that looks nice

**Comment by Hubza** [comment]
it'd stay in place as well as cubey moves, not follow

**Comment by rhythm-on-github** [comment]
ok at first that sounded really nice, but now (thinking about my HELL level) that would not always be nice xd

**Comment by Hubza** [comment]
why not

**Comment by Hubza** [comment]
![image](https://user-images.githubusercontent.com/33783503/97228304-9e366980-17ce-11eb-87ec-5901c1371afb.png)
fades out over time

**Comment by rhythm-on-github** [comment]
....the first second or two of HELL involves you falling really fast while spawning in, so that text would quickly disappear before the countdown even finishes xddddddddd

**Comment by Hubza** [comment]
well who needs a countdown

**Comment by rhythm-on-github** [comment]
Maybe make it such that it follows you while you're spawning, but after that stops following?

**Comment by Hubza** [comment]
that could work

**Comment by Hubza** [comment]
honestly you shouldnt even fall before your not spawned, just need to fix that

**Comment by rhythm-on-github** [comment]
naaah xd

**Comment by rhythm-on-github** [comment]
i think it's pretty funny that you can fall before existing

**Comment by Hubza** [comment]
i think its a bug

**Comment by rhythm-on-github** [comment]
it totally is, but i love it

**Comment by Hubza** [comment]
y'know that feeling when you havent been placed into existence yet but are already falling to your death?

yeah same
