### ISSUE TITLE
Add Discord Rich Presence

### ISSUE THREAD

**Issue by ariscript** [Team-Cubey/cubey#21]
Adding discord presence (rich or otherwise) would be nice and also is free publicity for the game. Manually adding to discord doesn't have an icon and it's kinda annoying

**Comment by Tanza3D** [comment]
things i have planned for this are:
- level number
- key count (possibly)
- current mappack (icon hover)
if you have any cool other ideas i'll see what i can do

**Comment by Tanza3D** [comment]
username on small image hover

**Comment by niilasoika** [comment]
I can agree with this!

**Comment by ariscript** [comment]
It's been like a month since the last thing happened here lol

**Comment by niilasoika** [comment]
i do know

**Comment by Tanza3D** [comment]
cubey is practically abandoned now

**Comment by niilasoika** [comment]
hold up



what??

**Comment by Tanza3D** [comment]
dm me  don't wanna spam this issue

**Comment by Tanza3D** [comment]
^ will be in rewrite
